# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f14217744d9de89b0c34be169ddc1c41b09402307efa3b1b8d646a28607479d28efb0cd97f53e68252279f74b3078dd9dd398a40b0868719a0c259858ba8514f

test:
  secret_key_base: ab77b1c85c4e4a6241414b5336f8662a5d74449bd5bdf83775d64dbdd21c39a6fba5e7043dd86e89c6166e9ff1aa0e15825bca070a81130920929b6072ff75e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
